import { images } from "../utilities/images";

export const marketTable = [
  {
    icon: images.usdt,
    name: "USDT",
    collateral: "$513.854",
    tvl: "29.3M",
    mcr: "150%",
    apr: "9.50%",
    details: "Details",
  },
  {
    icon: images.eth,
    name: "ETH",
    collateral: "$513.854",
    tvl: "29.3M",
    mcr: "150%",
    apr: "9.50%",
    details: "Details",
  },
  {
    icon: images.btc,
    name: "BTC",
    collateral: "$513.854",
    tvl: "29.3M",
    mcr: "190%",
    apr: "9.50%",
    details: "Details",
  },
  {
    icon: images.base,
    name: "BASE",
    collateral: "$513.854",
    tvl: "29.3M",
    mcr: "150%",
    apr: "9.50%",
    details: "Details",
  },
  {
    icon: images.bnb,
    name: "BNB",
    collateral: "$513.854",
    tvl: "29.3M",
    mcr: "150%",
    apr: "9.50%",
    details: "Details",
  },
];

export const supplyTable = [
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    supply: "Supply",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    supply: "Supply",
    details: "Details",
  },
  {
    icon: images.bnb,
    name: " BNB",
    balance: "$0.372bnb",
    apy: "7.8%",
    status: "Inactive",
    supply: "Supply",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    supply: "Supply",
    details: "Details",
  },
  {
    icon: images.usdt,
    name: " USDT",
    balance: "1.963usdt",
    apy: "2.9%",
    status: "Inactive",
    supply: "Supply",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    supply: "Supply",
    details: "Details",
  },
];
export const borrowTable = [
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    borrow: "Borrow",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    borrow: "borrow",
    details: "Details",
  },
  {
    icon: images.bnb,
    name: " BNB",
    balance: "$0.372bnb",
    apy: "7.8%",
    status: "Inactive",
    borrow: "borrow",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    borrow: "borrow",
    details: "Details",
  },
  {
    icon: images.usdt,
    name: " USDT",
    balance: "1.963usdt",
    apy: "2.9%",
    status: "Inactive",
    borrow: "borrow",
    details: "Details",
  },
  {
    icon: images.eth,
    name: " cbETH",
    balance: "0.653eth",
    apy: "0.4%",
    status: "Live",
    borrow: "borrow",
    details: "Details",
  },
];

export const wallets = [
  {
    icon: images.metamask,
    name: "Browser Wallet",
  },

  {
    icon: images.coinbase,
    name: "Coinbase Wallet",
  },

  {
    icon: images.walletConnect,
    name: "WalletConnect",
  },
];
