import type { Metadata } from "next";
import { Inter } from "next/font/google";

import DashboardNavBar from "../components/navbar/DashboardNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black pb-24 min-h-screen w-full">
          <DashboardNavBar />
          <br /> <br />
          {children}
        </div>
      </body>
    </html>
  );
}
